const profiles=[{n:'V8',s:'MUSCLE',base:46,mul:1.00,wave:'sawtooth'},{n:'SC V8',s:'SUPERCHARGED',base:52,mul:1.05,wave:'sawtooth'},{n:'JDM',s:'TURBO',base:68,mul:1.18,wave:'square'},{n:'STARSHIP',s:'TURBINE',base:92,mul:1.42,wave:'sine'},{n:'KINGS',s:'SIGNATURE',base:38,mul:.88,wave:'sawtooth'}];const $=x=>document.querySelector(x);let selected=0,watch=null,manual=false,lastSpeed=0,lastT=Date.now(),lastGear='P',ctx=null,master=null,osc1=null,osc2=null,filter=null,lfo=null,lfoGain=null,audioOn=false,currentRPM=800,currentAccel=0;
profiles.forEach((p,i)=>{let b=document.createElement('button');b.className='mode'+(i===0?' active':'');b.innerHTML=p.n+'<small>'+p.s+'</small>';b.onclick=()=>{selected=i;document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#modeName').textContent=p.n;if(audioOn)applySound()};$('#modes').appendChild(b)});
function initAudio(){if(ctx){ctx.resume();return}ctx=new (window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();filter=ctx.createBiquadFilter();filter.type='lowpass';filter.Q.value=2;osc1=ctx.createOscillator();osc2=ctx.createOscillator();let g1=ctx.createGain(),g2=ctx.createGain();g1.gain.value=.34;g2.gain.value=.16;lfo=ctx.createOscillator();lfoGain=ctx.createGain();lfo.frequency.value=7;lfoGain.gain.value=7;lfo.connect(lfoGain);lfoGain.connect(osc1.frequency);osc1.connect(g1);osc2.connect(g2);g1.connect(filter);g2.connect(filter);filter.connect(master);master.connect(ctx.destination);osc1.start();osc2.start();lfo.start();audioOn=true;$('#audio').textContent='AUDIO ACTIVE';$('#power').textContent='SOUND ON';applySound()}
function applySound(){if(!audioOn)return;let p=profiles[selected],t=ctx.currentTime,r=currentRPM/800,th=Math.min(1,Math.max(0,currentAccel/8));osc1.type=p.wave;osc2.type=p.n==='STARSHIP'?'sine':'triangle';osc1.frequency.setTargetAtTime(p.base*r*p.mul,t,.045);osc2.frequency.setTargetAtTime(p.base*2.02*r*p.mul,t,.05);filter.frequency.setTargetAtTime(Math.min(4800,300+currentRPM*.55+th*1000),t,.06);let vol=(+$('#volume').value/100)*(+$('#intensity').value/100);master.gain.setTargetAtTime(vol*(.08+th*.055),t,.06);lfo.frequency.setTargetAtTime(5+r*2,t,.08)}
function calc(mph,accel){let points=[0,18,34,52,73,98],g=mph<1?'P':Math.min(6,points.filter(x=>mph>=x).length),base=g==='P'?800:1250+((mph-(points[g-1]||0))/Math.max(1,(points[g]||125)-(points[g-1]||0)))*5000,rpm=Math.round(Math.min(7400,Math.max(750,base+Math.max(0,accel)*430)));return{g,rpm}}
function render(mph,accel=0){mph=Math.max(0,mph);let o=calc(mph,accel);if(o.g!==lastGear&&lastGear!=='P'&&o.g!=='P'){$('#shift').classList.remove('flash');void $('#shift').offsetWidth;$('#shift').classList.add('flash')}lastGear=o.g;currentRPM=o.rpm;currentAccel=accel;$('#speed').textContent=Math.round(mph);$('#gear').textContent=o.g;$('#rpm').textContent=o.rpm;$('#rpmbar').style.width=Math.min(100,o.rpm/74)+'%';$('#engineState').textContent=o.rpm<1100?'IDLE':o.rpm>6000?'REDLINE':accel>1.5?'PULL':'CRUISE';applySound()}
$('#power').onclick=()=>{if(!audioOn){initAudio()}else{let on=master.gain.value>0;if(on){master.gain.setTargetAtTime(0,ctx.currentTime,.05);$('#power').textContent='SOUND OFF';$('#audio').textContent='AUDIO MUTED'}else{$('#power').textContent='SOUND ON';$('#audio').textContent='AUDIO ACTIVE';applySound()}}};
$('#manual').onclick=()=>{manual=!manual;$('#throttleWrap').classList.toggle('hidden',!manual);$('#manual').textContent=manual?'EXIT MANUAL':'MANUAL TEST';$('#inputState').textContent=manual?'MANUAL':'STANDBY';if(manual&&watch){navigator.geolocation.clearWatch(watch);watch=null;$('#gps').textContent='GPS OFF'}};
$('#throttle').oninput=e=>{if(!audioOn)initAudio();let v=+e.target.value;$('#throttleVal').textContent=v+'%';render(v*1.15,v/15)};
$('#volume').oninput=e=>{$('#volumeVal').textContent=e.target.value+'%';applySound()};$('#intensity').oninput=e=>{$('#intensityVal').textContent=e.target.value+'%';applySound()};
$('#start').onclick=()=>{if(!audioOn)initAudio();if(!navigator.geolocation){$('#gps').textContent='GPS UNSUPPORTED';return}manual=false;$('#throttleWrap').classList.add('hidden');$('#inputState').textContent='GPS';$('#gps').textContent='GPS CONNECTING';if(watch)navigator.geolocation.clearWatch(watch);watch=navigator.geolocation.watchPosition(p=>{let now=Date.now(),mph=Math.max(0,(p.coords.speed||0)*2.23694),dt=Math.max(.25,(now-lastT)/1000),acc=(mph-lastSpeed)/dt;lastSpeed=mph;lastT=now;$('#gps').textContent='GPS ACTIVE';render(mph,acc)},()=>{$('#gps').textContent='GPS UNAVAILABLE';$('#inputState').textContent='MANUAL READY'},{enableHighAccuracy:true,maximumAge:300,timeout:10000})};render(0);

// CC0 sampled engine layer
const sampleUrls=[
  'https://opengameart.org/sites/default/files/loop_0.wav',
  'https://opengameart.org/sites/default/files/loop_1_0.wav',
  'https://opengameart.org/sites/default/files/loop_2_0.wav',
  'https://opengameart.org/sites/default/files/loop_3_0.wav',
  'https://opengameart.org/sites/default/files/loop_4_0.wav',
  'https://opengameart.org/sites/default/files/loop_5_0.wav'
];
const samplePlayers=sampleUrls.map((src,i)=>{const a=new Audio(src);a.loop=true;a.preload='auto';a.volume=0;return a});
let samplesStarted=false;
function startSamples(){if(samplesStarted)return;samplePlayers.forEach(a=>a.play().catch(()=>{}));samplesStarted=true}
function updateSamples(){if(!audioOn||!samplesStarted)return;const x=Math.max(0,Math.min(5,(currentRPM-800)/1100));const lo=Math.floor(x),hi=Math.min(5,lo+1),mix=x-lo;const masterVol=(+$('#volume').value/100)*(+$('#intensity').value/100);samplePlayers.forEach((a,i)=>{let w=0;if(i===lo)w=1-mix;if(i===hi)w=Math.max(w,mix);a.volume=Math.min(.72,w*masterVol*.7);a.playbackRate=profiles[selected].n==='JDM'?1.08:profiles[selected].n==='STARSHIP'?1.16:1});}
const oldApply=applySound;applySound=function(){oldApply();updateSamples()};
const oldInit=initAudio;initAudio=function(){oldInit();startSamples();updateSamples()};
